/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cn.edu.pku.gui;

import FProject.FProject;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

/**
 *
 * @author 冯雨宁
 */
public class CreateFProject extends javax.swing.JFrame implements ActionListener{

    JPanel jp1,jp2;//面板
    JLabel jlb1;//标签
    JButton jbtnOK, jbtnCancel;//按钮
    JTextField jtfFPName;//文本
    Main_win fMain;

    /**
     * Creates new form CreateFProject
     */
    public CreateFProject(Main_win main) {
        initComponents();
        
        fMain=main;
        
        //创建面板 
        jp1=new JPanel();
        jp2=new JPanel();
        
        //创建标签
        jlb1=new JLabel("Project Name");
        
        //创建按钮
        jbtnOK= new JButton("OK");
        jbtnCancel=new JButton("Cancel");
        
        //创建文本框
        jtfFPName=new JTextField(20);
      
        
        //设置布局管理
        this.setLayout(new GridLayout(4,1));
        
        //加入组件
        jp1.add(jlb1);
        jp1.add(jtfFPName);
        
        jp2.add(jbtnOK);
        jp2.add(jbtnCancel);
        
        //加入到JFrame
        this.add(new JPanel(null));
        this.add(jp1);
        this.add(jp2);
        this.add(new JPanel(null));

        //设置窗体
        this.setTitle("New Project");
        this.setSize(350,200);
        this.setLocationRelativeTo(null);//屏幕中间显示
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);//退出关闭
        this.setVisible(true);
        
        //锁定窗体
        this.setResizable(false);   
        
        //按钮监听
        jbtnOK.addActionListener(this);
        jbtnCancel.addActionListener(this);
        
        //键盘回车监听
        KeyListener keyListener_create=new KeyListener(){
            public void keyTyped(KeyEvent e){}
            public void keyReleased(KeyEvent e){}
            public void keyPressed(KeyEvent e){
                if(e.getKeyChar()==KeyEvent.VK_ENTER)
                {
                    createNewFProject(jtfFPName.getText());    
                }
            }
        };       
        
        jtfFPName.addKeyListener(keyListener_create);
    }
    
    public void actionPerformed(ActionEvent e){
        if(e.getActionCommand()=="OK")
        {
            createNewFProject(jtfFPName.getText());   
        }
        else if(e.getActionCommand()=="Cancel")
        {
            dispose();
        }
    }
    
    public void createNewFProject(String name){
        String title= "FreeStyle-"+name + ".prj";
        fMain.setTitle(title);
        dispose();
        JOptionPane.showMessageDialog(null,"Project "+jtfFPName.getText()+"\n is created successfully !","FreeStyle",JOptionPane.INFORMATION_MESSAGE);   
        fMain.mFProject=new FProject(name);
        this.fMain.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateFProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateFProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateFProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateFProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CreateFProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
